### ISSUE TITLE
How to get transaction hash from Substrate transfer destination chain in ui application?

### ISSUE THREAD

**Issue by Dmitriy1984Molchanov** [ChainSafe/sygma-ui#262]
We are transferring tokens from the Ethereum-based network to the Substrate-based and want to see the transaction hash from the destination chain in the UI application.

How can we achieve this? Is it possible to do it by nonce?

**Comment by wainola** [comment]
Hi, we are not supporting `substrate` networks at the moment. We have plans to do it in the foreseeable. As for today, the UI doesn't support this anymore.

**Comment by Dmitriy1984Molchanov** [comment]
I see, maybe you know some mechanism.

**Comment by Dmitriy1984Molchanov** [comment]
Do you have any dates when you plan to start supporting substrate?

**Comment by Dmitriy1984Molchanov** [comment]
Why did you decide to remove Substrate support?  You supported it before and it's not clear why did you decide to remove its support? Just wanted to understand the reasons.
